name: cocoapods

on:
  push:

permissions:
  contents: write
  issues: write  # Needed to create issues for manual approval

jobs:
  build-and-upload-testflight:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build and Upload to TestFlight
        run: echo "Build and upload steps go here"

  build-cocoapods:
    needs: [build-and-upload-testflight]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build CocoaPods
        run: echo "Build CocoaPods steps go here"

      - name: Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: cfabianleon
          minimum-approvals: 1
          issue-title: "Approval needed"
          issue-body: "Please approve or deny the upload for cocoa pods."

          
  upload-to-s3:
    needs: [build-cocoapods]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Upload to S3
        run: echo "Upload to S3 steps go here"

  push-to-cocoapods:
    needs: [upload-to-s3]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to CocoaPods
        run: echo "Push to CocoaPods steps go here"

