name: Paso 0, Inicializar repo

# This step triggers after the learner creates a new repository from the template
# This step sets STEP to 1
# This step closes <details id=0> and opens <details id=1>

# This will run every time we create push a commit to `main`
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  push:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Do you want to publish to CocoaPods?'
        required: true
        default: 'no'
        type: choice
        options:
        - yes
        - no


# Reference https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:
  # Get the current step from .github/script/STEP so we can
  # limit running the main job when the learner is on the same step.
  build-and-upload-testflight:
    name: Verificar paso actual
    runs-on: ubuntu-latest
    steps:
      - name: Await manual approval before publishing to CocoaPods
        run: echo "Manual approval required to proceed with publishing to CocoaPods."

  manual-approval:
    needs: build-and-upload-testflight
    runs-on: ubuntu-latest
    steps:
      - name: Await manual approval before publishing to CocoaPods
        run: echo "Manual approval required to proceed with publishing to CocoaPods."

  build-cocoapods:
    if: ${{ inputs.publish == 'yes' }}
    needs: [manual-approval]
    runs-on: ubuntu-latest
    steps:
      - name: Await manual approval before publishing to CocoaPods
        run: echo "Manual approval required to proceed with publishing to CocoaPods."
        
  upload-to-s3:
    name: Verificar paso actual
    needs: [build-cocoapods]
    runs-on: ubuntu-latest
    steps:
      - name: Await manual approval before publishing to CocoaPods
        run: echo "Manual approval required to proceed with publishing to CocoaPods."

  push-to-cocoapods:
    name: Verificar paso actual
    needs: [build-cocoapods]
    runs-on: ubuntu-latest
    steps:
      - name: Await manual approval before publishing to CocoaPods
        run: echo "Manual approval required to proceed with publishing to CocoaPods."
      