name: Marvel Movies List
on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Do you want to publish to CocoaPods?'
        required: true
        default: 'no'
        type: choice
        options:
          - 'yes'
          - 'no'

jobs:
  wolverine:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.publish == 'yes' }}
    steps:
      - run: echo "wolverine"
  

