name: Addition Workflow

on:
  pull_request:
    branches:
      - main 
  workflow_dispatch:
    inputs:
      number1:
        description: 'First number'
        required: true
        default: '1'
      number2:
        description: 'Second number'
        required: true
        default: '1'


jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Add Numbers
        run: node add.js ${{ github.event.inputs.number1 }} ${{ github.event.inputs.number2 }}
